### 1. Tensors

In [1]:
import torch
import numpy as np

Initialising

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

Convert from numpy

In [3]:
arr = np.array(data)
x_data = torch.from_numpy(arr)
x_data

tensor([[1, 2],
        [3, 4]])

From other tensors

In [4]:
x_1 = torch.ones_like(x_data)
x_0 = torch.zeros_like(x_data)

x_1, x_0

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0, 0],
         [0, 0]]))

In [6]:
x_r = torch.rand_like(x_data, dtype=torch.float)
x_r

tensor([[0.2556, 0.0633],
        [0.3536, 0.8195]])

Tensor of a fixed shape

In [7]:
shape = (2, 3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.tensor(shape)
zeros_tensor = torch.tensor(shape)

Attributes of a tensor

In [8]:
rand_tensor.shape

torch.Size([2, 3])

In [9]:
rand_tensor.dtype

torch.float32

In [10]:
rand_tensor.device

device(type='cpu')

Move tensor to GPU if available

Indexing and Slicing

In [24]:
x = torch.ones(3, 4)
print(x)
print('first row: ', x[0])
print('first col: ', x[:, 0])
print('first element: ', x[0, 0])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first row:  tensor([1., 1., 1., 1.])
first col:  tensor([1., 1., 1.])
first element:  tensor(1.)


In [25]:
#set 2nd col to 0
x[:, 1] = 0
x

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Join tensors along a given axis

In [26]:
x = torch.cat([x, x, x], dim=1)
x

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [27]:
x.shape

torch.Size([3, 12])

Concat along a new dimension

In [32]:
y = torch.stack([x, x], dim=0)
y.shape

torch.Size([2, 3, 12])

In [33]:
print(y)

tensor([[[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]],

        [[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]])


In [11]:
if torch.cuda.is_available():
    rand_tensor.to('cuda')

In [36]:
y = torch.stack([x, x], dim=2)
y.shape

torch.Size([3, 12, 2])

In [37]:
print(y)

tensor([[[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]]])


Matrix multiplication

In [39]:
shape = [3, 4]
x = torch.rand(shape)

In [40]:
y1 = x @ x.T

In [41]:
y1

tensor([[2.1705, 1.4155, 1.9742],
        [1.4155, 1.0882, 1.4637],
        [1.9742, 1.4637, 2.5134]])

In [42]:
y2 = torch.matmul(x, x.T)
y2

tensor([[2.1705, 1.4155, 1.9742],
        [1.4155, 1.0882, 1.4637],
        [1.9742, 1.4637, 2.5134]])

In [43]:
y3 = x.matmul(x.T)
y3

tensor([[2.1705, 1.4155, 1.9742],
        [1.4155, 1.0882, 1.4637],
        [1.9742, 1.4637, 2.5134]])

Elementwise multiplication

In [44]:
z1 = x * x
z2 = torch.mul(x, x)
z3 = x.mul(x)

In [49]:
print(torch.eq(z1, z2))
print(torch.eq(z1, z3))

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Single element tensor

In [50]:
agg = x.sum()
agg = agg.item()
agg

7.753596305847168

In place operations

In [51]:
x.add_(5)
x

tensor([[5.3797, 5.7147, 5.9178, 5.8205],
        [5.5659, 5.2345, 5.6882, 5.4893],
        [5.9797, 5.8726, 5.8594, 5.2314]])

Bridge with numpy

Tensors on cpu and gpu share memory and changing one changes the other

Numpy array created from tensor share memory and vice versa

In [52]:
t = torch.ones([3,3])
n = t.numpy()
n

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [53]:
t.add_(1)
n

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)

Numpy to tensor

In [54]:
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [55]:
np.add(n, 1, out=n)
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

************

### 2. Datasets and Dataloaders

torch.utils.data.Dataset stores data and the labels

torch.utils.data.DataLoader wraps an iterable around Dataset

In [5]:
import torch
import numpy as np
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

In [7]:
train_data = datasets.FashionMNIST(
                                    root='data',
                                    train=True,
                                    download=True,
                                    transform=ToTensor() 
                                )

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

In [ ]:
test_data = datasets.Fa
