Tensors

In [1]:
import torch
import numpy as np

Initialising

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

Convert from numpy

In [3]:
arr = np.array(data)
x_data = torch.from_numpy(arr)
x_data

tensor([[1, 2],
        [3, 4]])

From other tensors

In [4]:
x_1 = torch.ones_like(x_data)
x_0 = torch.zeros_like(x_data)

x_1, x_0

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0, 0],
         [0, 0]]))

In [6]:
x_r = torch.rand_like(x_data, dtype=torch.float)
x_r

tensor([[0.2556, 0.0633],
        [0.3536, 0.8195]])

Tensor of a fixed shape

In [7]:
shape = (2, 3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.tensor(shape)
zeros_tensor = torch.tensor(shape)

Attributes of a tensor

In [8]:
rand_tensor.shape

torch.Size([2, 3])

In [9]:
rand_tensor.dtype

torch.float32

In [10]:
rand_tensor.device

device(type='cpu')

Move tensor to GPU if available

In [11]:
if torch.cuda.is_available():
    rand_tensor.to('cuda')

Indexing and Slicing

In [24]:
x = torch.ones(3, 4)
print(x)
print('first row: ', x[0])
print('first col: ', x[:, 0])
print('first element: ', x[0, 0])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first row:  tensor([1., 1., 1., 1.])
first col:  tensor([1., 1., 1.])
first element:  tensor(1.)


In [25]:
#set 2nd col to 0
x[:, 1] = 0
x

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Join tensors along a given axis

In [26]:
x = torch.cat([x, x, x], dim=1)
x

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [27]:
x.shape

torch.Size([3, 12])

Concat along a new dimension

In [32]:
y = torch.stack([x, x], dim=0)
y.shape

torch.Size([2, 3, 12])

In [33]:
print(y)

tensor([[[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]],

        [[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]])


In [36]:
y = torch.stack([x, x], dim=2)
y.shape

torch.Size([3, 12, 2])

In [37]:
print(y)

tensor([[[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]]])
